export const CONSULTA_PERSONAJE = "CONSULTA_PERSONAJES";
export const DELETE_PERSONAJE = "DELETE_PERSONAJE";
export const DETAIL_PERSONAJE = "DETAIL_PERSONAJE";
export const MANAGEADD_FAVORITES = "MANAGEADD_FAVORITES"
export const MANAGEDELETE_FAVORITES = "MANAGEDELETE_FAVORITES"
